### ISSUE TITLE
[Unsupported device] GROUP

### ISSUE THREAD

**Issue by DevEddy** [larsbeck/HomematicIp#21]
Hi Lars,

it's me again ;) Could you help me to fix this?

HomematicIp.Data.UnknownHomematicObjectException: GROUP:
```json
{
	"id": "3c9f049b-44be-4fe6-a1fa-f79ecea6e775",
	"homeId": "72b59664-171b-4c61-8714-0da4df6f617c",
	"metaGroupId": null,
	"label": "Rolläden Obergeschoss",
	"lastStatusUpdate": 1571044960331,
	"unreach": false,
	"lowBat": null,
	"dutyCycle": false,
	"type": "SHUTTER_PROFILE",
	"channels": [{
		"deviceId": "3014F711A0001118A99511FD",
		"channelIndex": 1
	}, {
		"deviceId": "3014F711A000111A499146F9",
		"channelIndex": 1
	}],
	"processing": false,
	"shutterLevel": 0.0,
	"primaryShadingLevel": 0.0,
	"primaryShadingStateType": "POSITION_USED",
	"slatsLevel": null,
	"secondaryShadingLevel": null,
	"secondaryShadingStateType": "NOT_EXISTENT",
	"profileId": "56775a2b-5c47-494c-90bd-8ec8605ff732",
	"profileMode": "AUTOMATIC"
}
```

Thanks,
Eddy

**Comment by larsbeck** [comment]
Hi Eddy,

what appears to be the problem here? I was able to parse this bit fine with the current version (I pulled your commits before - thanks btw!).

![2019-10-14_16h09_12](https://user-images.githubusercontent.com/1286096/66757751-1d475100-ee9d-11e9-8414-23da576305af.png)

Lars

**Comment by DevEddy** [comment]
I think it's fixed now, I've added SHUTTER_PROFILE,
Thanks for the fast response

Eddy
