### ISSUE TITLE
[Unsupported device GROUP] HOT_WATER

### ISSUE THREAD

**Issue by DevEddy** [larsbeck/HomematicIp#24]
Hi Lars,

I've got this message:

HomematicIp.Data.UnknownHomematicObjectException: Unsupported device GROUP:
```json
{
	"id": "3cb2b623-21e9-4c02-ba8f-0c471a3e6d05",
	"homeId": "2d896258-5f1f-4eca-96c5-e791a23128d2",
	"metaGroupId": null,
	"label": "HOT_WATER",
	"lastStatusUpdate": 0,
	"unreach": null,
	"lowBat": null,
	"dutyCycle": null,
	"type": "HOT_WATER",
	"channels": [],
	"on": null,
	"onTime": 900.0,
	"profileId": "16192fe0-bf8f-4ffe-9f51-31ff97624811",
	"profileMode": null
}
```

Could you help me fix it?

Thanks,
Eddy

**Comment by larsbeck** [comment]
Hi Eddy,

I have added support for HotWater Groups. Also, I had to remove the EnumMap from your new class MultiModeInputChannel, since that broke the code because the same EnumMap was also assigned to FullFlushContactInterface. Maybe you want to revisit that.

Lars

**Comment by DevEddy** [comment]
Hi Lars,

thanks, I already fixed it, I just forgot to rename it correctly :D...

Eddy
