### ISSUE TITLE
Bad Request during authorization

### ISSUE THREAD

**Issue by SaschaWeisenberger** [larsbeck/HomematicIp#27]
Hi, I just tried to run the console app, but I always get an error when trying to look up the host (https://github.com/larsbeck/HomematicIp/blob/master/src/HomematicIp/Services/HomematicServiceBase.cs#L48)

Here is what Fillder says what the request body looks like:
![image](https://user-images.githubusercontent.com/21291058/69917936-1b951500-146c-11ea-9927-071a872f9ce7.png)
(plus id of course, I've double checked, it is correct)

Any idea what could be the problem?

**Comment by larsbeck** [comment]
Hi Sascha,

the clientCharacteristics look ok. What does the error message say?

**Comment by SaschaWeisenberger** [comment]
StatusCode and ReasonPhrase are both "Bad Request". Is there anything else I can check?

**Comment by larsbeck** [comment]
Here is an idea: Is there a chance that you typed your SGTIN with dashes? It needs to be typed without dashes in the config.

**Comment by SaschaWeisenberger** [comment]
of course with dashes -.- 
sorry, I will try it without dashes when I'm back home, thanks for your help! (a small comment in the config would be nice ;) )

**Comment by larsbeck** [comment]
Yes, agreed. I'll actually change the code to allow dashes.

**Comment by SaschaWeisenberger** [comment]
even better ^^ looking forward to use this api! I have great plans...
