### ISSUE TITLE
HEATING_THERMOSTAT_COMPACT device missing

### ISSUE THREAD

**Issue by obartelt** [larsbeck/HomematicIp#28]
The HEATING_THERMOSTAT_COMPACT device is missing. Otherwise, great work!

**Comment by larsbeck** [comment]
Thanks for the kind words! I can add the device, but I will need the Json object from the UnknownHomematicObjectException. You can see what it roughly looks like in one of the closed issues, like https://github.com/larsbeck/HomematicIp/issues/24
Or if you can add the device yourself, feel free to send me a pull request.

**Comment by obartelt** [comment]
I assume it's just the same as HEATING_THERMOSTAT. At least I copied the device into another class, and it works. Maybe there are additional properties, but the de-serialization works, at least. After all, it's just another heating thermostat, just compact ;-)

**Comment by larsbeck** [comment]
I have added HEATING_THERMOSTAT_COMPACT to the EnumMap of HeatingThermostat. Thanks for reporting this!
